version: "3.1"

services:
  api:
    image: <%= projectName %>
    container_name: <%= projectName %>
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - postgres
    networks: 
      - default
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: 
      - default
    env_file:
      - .env

volumes:
  db_data:

networks: 
  default:
    driver: bridge